#-------------------------------
# General Site Settings

title: Jacob Claessens Theme | Theme for Jekyll
description: Jacob Claessens is an easy and simple theme for Jekyll. Dark colors, give it a special exquisite look. A careful approach to design and features make it an ideal solution for a personal blog. # this means to ignore newlines until "baseurl:"
# baseurl: "/JacobClaessens" # the subpath of your site, e.g. /blog
# url: "/JacobClaessens" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" #"claessens14.github.io" # the subpath of your site, e.g. /blog
url: "JacobsWebsite" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
author-name:   Jacob Claessens
author-avatar: profile-pic.jpeg


#-------------------------------
# Contact links
facebook:  https://facebook.com/ # Add your Facebook handle
twitter:   https://twitter.com/Jacob72477571 # Add your Facebook handle
github: https://github.com/Claessens14
instagram: https://www.instagram.com/claesseus14/ # Add your Facebook handle
pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
